[package]
name = "template-replacement-core-wasm"
description = "模板替换核心wasm库"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common", features = ["general"] }
wasm-bindgen.workspace = true
js-sys.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
