[package]
name = "template-replacement-core-wasm"
version = "1.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3  # 最大化性能
lto = true       # 启用链接时优化
codegen-units = 1
panic = 'abort'  # 出现 panic 时直接终止程序
