[package]
name = "template-replacement-core-wasm-polyfill"
version = "1.8.5"
edition = "2024"
description = "模板替换核心wasm库"
license = "Apache 2.0"

[dependencies]
common = { path = "../common", features = ["general"] }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[package.metadata.wasm-bindgen]
disable_multi_value = true