[package]
name = "common"
version = "1.8.5"
edition = "2024"

[dependencies]
regex = "1.11.1"
wasm-bindgen = { version = "0.2.99" }
zip = { version = "8.6.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }
console_log = "1.0.0"
log = "0.4.22"
console_error_panic_hook = "0.1.7"
serde = { version = "1.0.216", default-features = false, features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
js-sys = "0.3.76"
rmp-serde = "1.3.0"
base64 = "0.22.1"
aes = "0.9.1"
cipher = "0.5.2"
ofb = "0.7.1"
flate2 = "1.1.5"

[dev-dependencies]
console_error_panic_hook = "0.1.7"
async-std = { version = "1.13.0", features = ["attributes"] }

[lib]
name = "common"
path = "src/lib.rs"

[features]
general = []
param-sign = []
