name: template-replacement-core-wasm

on:
  push:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - run: cd general/pkg && npm publish
      - run: cd general-polyfill/pkg && npm publish
      - run: cd sign/pkg && npm publish
      - run: cd sign-polyfill/pkg && npm publish
